const API_URL = "https://imperium-api.imperiumlj.workers.dev";
const DEFAULT_CONFIG = {
  nome_empresa:"IMPÉRIUM Lava Jato e Estacionamento", whatsapp:"(16) 99357-5780", instagram:"@imperium_lavajato", instagram_url:"https://instagram.com/imperium_lavajato", endereco:"Rua General Carneiro, 695 — Estação — Franca/SP", cnpj:"65.675.125/0001-67", horario_presencial:"08:00 às 17:00", horario_antecipado:"06:30", antecedencia_chegada_minutos:"10", tolerancia_minutos:"10",
  desconto_5_min:"200", desconto_5_percentual:"5", desconto_10_min:"250", desconto_10_percentual:"10", desconto_15_min:"300", desconto_15_percentual:"15", desconto_25_min:"600", desconto_25_percentual:"25",
  motor_aviso:"A lavagem de motor envolve riscos com água e produtos químicos. Mesmo com proteção de módulos, bornes, sensores e outros componentes, podem ocorrer falhas ou problemas relacionados a condições pré-existentes.", motor_resfriamento_horas:"3", motor_termo_checkbox:"Li e estou ciente dos riscos envolvidos na lavagem de motor."
};
let SITE_CONFIG = {...DEFAULT_CONFIG};
let SERVICES = [];
function money(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0)}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
async function api(path,options={}){const r=await fetch(API_URL+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let data={};try{data=await r.json()}catch{}if(!r.ok||data.sucesso===false)throw new Error(data.erro||'Erro na comunicação com o sistema.');return data}
async function loadConfig(){try{const d=await api('/api/configuracoes');SITE_CONFIG={...DEFAULT_CONFIG,...(d.configuracoes||{})}}catch(e){console.warn('Configuração:',e)}applyConfig()}
function applyConfig(){document.querySelectorAll('[data-config]').forEach(el=>{const k=el.dataset.config;if(SITE_CONFIG[k]!==undefined)el.textContent=SITE_CONFIG[k]});const w=String(SITE_CONFIG.whatsapp||'').replace(/\D/g,'');const wl=document.getElementById('whatsapp-link');if(wl&&w)wl.href='https://wa.me/55'+w;const il=document.getElementById('instagram-link');if(il)il.href=SITE_CONFIG.instagram_url||'https://instagram.com/imperium_lavajato';const gm=document.getElementById('google-maps-link');if(gm&&SITE_CONFIG.google_maps_url)gm.href=SITE_CONFIG.google_maps_url;const title=document.getElementById('page-title');if(title)title.textContent=SITE_CONFIG.seo_titulo||title.textContent;const meta=document.getElementById('meta-description');if(meta&&SITE_CONFIG.seo_descricao)meta.content=SITE_CONFIG.seo_descricao}
async function loadServices(){const d=await api('/api/servicos');SERVICES=d.servicos||[];return SERVICES}
function isBase(s){return /lavagem/i.test(String(s.categoria||''))||/^lavagem/i.test(String(s.nome||''))}
function servicePrice(s){return Number(s.preco)||0}
function servicePendingPrice(s){return String(s.preco_tipo||'fixo')==='a_partir_de'}
function serviceName(s){return s.nome||'Serviço'}
function selectedIds(){return {base:Number(localStorage.getItem('imperiumBaseId')||0),addons:JSON.parse(localStorage.getItem('imperiumAddonIds')||'[]').map(Number)}}
function saveIds(base,addons){localStorage.setItem('imperiumBaseId',String(base||''));localStorage.setItem('imperiumAddonIds',JSON.stringify(addons.map(Number)))}
function discounts(){return [{min:Number(SITE_CONFIG.desconto_25_min)||600,rate:(Number(SITE_CONFIG.desconto_25_percentual)||25)/100,label:(Number(SITE_CONFIG.desconto_25_percentual)||25)+'%'},{min:Number(SITE_CONFIG.desconto_15_min)||300,rate:(Number(SITE_CONFIG.desconto_15_percentual)||15)/100,label:(Number(SITE_CONFIG.desconto_15_percentual)||15)+'%'},{min:Number(SITE_CONFIG.desconto_10_min)||250,rate:(Number(SITE_CONFIG.desconto_10_percentual)||10)/100,label:(Number(SITE_CONFIG.desconto_10_percentual)||10)+'%'},{min:Number(SITE_CONFIG.desconto_5_min)||200,rate:(Number(SITE_CONFIG.desconto_5_percentual)||5)/100,label:(Number(SITE_CONFIG.desconto_5_percentual)||5)+'%'}].sort((a,b)=>b.min-a.min)}
function calcOrder(){const ids=selectedIds();const base=SERVICES.find(s=>Number(s.id)===ids.base);const addons=ids.addons.map(id=>SERVICES.find(s=>Number(s.id)===id)).filter(Boolean);const items=base?[base,...addons]:[];const subtotal=items.reduce((a,s)=>a+servicePrice(s),0);const disc=discounts().find(x=>subtotal>=x.min)||{min:0,rate:0,label:'0%'};const pendingPrice=items.some(servicePendingPrice);const pendingDuration=items.some(s=>!Number(s.duracao_minutos));return {base,addons,items,subtotal,discount:disc,discountValue:subtotal*disc.rate,total:subtotal*(1-disc.rate),pendingPrice,pendingDuration,minutes:pendingDuration?null:items.reduce((a,s)=>a+Number(s.duracao_minutos),0)}}
function renderSelected(target,order){const el=document.getElementById(target);if(!el)return;el.innerHTML=order.items.length?order.items.map((s,i)=>`<div class="selected-item"><span>${i===0?'<b>Base:</b> ':''}${esc(serviceName(s))}</span><strong>${servicePendingPrice(s)?'A partir de '+money(s.preco):money(s.preco)}</strong></div>`).join(''):'<div class="selected-item"><span>Escolha um serviço para começar.</span><strong>—</strong></div>'}
async function renderBuilder(){const baseEl=document.getElementById('base-services');if(!baseEl)return;await loadConfig();await loadServices();const bases=SERVICES.filter(isBase);const addons=SERVICES.filter(s=>!isBase(s));let ids=selectedIds();if(!bases.length&&SERVICES.length)ids.base=Number(SERVICES[0].id);if(!bases.some(s=>Number(s.id)===ids.base))ids.base=Number(bases[0]?.id||SERVICES[0]?.id||0);ids.addons=ids.addons.filter(id=>addons.some(s=>Number(s.id)===id));saveIds(ids.base,ids.addons);baseEl.innerHTML=bases.length?bases.map(s=>`<label class="option-card"><input type="radio" name="base-service" value="${s.id}" ${Number(ids.base)===Number(s.id)?'checked':''}><span><h3>${esc(serviceName(s))}</h3><small>${esc(s.descricao||'')}</small></span><span class="option-price">${servicePendingPrice(s)?'A partir de '+money(s.preco):money(s.preco)}</span></label>`).join(''):'<div class="empty-state">Nenhum serviço principal cadastrado.</div>';const addonEl=document.getElementById('addons');addonEl.innerHTML=addons.length?addons.map(s=>`<label class="option-card"><input class="addon-check" type="checkbox" value="${s.id}" ${ids.addons.includes(Number(s.id))?'checked':''}><span><h3>${esc(serviceName(s))}</h3><small>${esc(s.descricao||'')}</small></span><span class="option-price">${servicePendingPrice(s)?'A partir de '+money(s.preco):money(s.preco)}</span></label>`).join(''):'<div class="empty-state">Nenhum adicional cadastrado no momento.</div>';baseEl.onchange=updateBuilder;addonEl.onchange=updateBuilder;const mh=document.getElementById('motor-hours');if(mh)mh.textContent=SITE_CONFIG.motor_resfriamento_horas||3;const mw=document.getElementById('motor-warning');if(mw)mw.textContent=SITE_CONFIG.motor_aviso||DEFAULT_CONFIG.motor_aviso;const ml=document.getElementById('motor-checkbox-label');if(ml)ml.textContent=SITE_CONFIG.motor_termo_checkbox||DEFAULT_CONFIG.motor_termo_checkbox;updateBuilder()}
function hasMotor(order){return order.items.some(s=>/motor/i.test(s.nome||''))}
function updateBuilder(){const base=Number(document.querySelector('input[name="base-service"]:checked')?.value||0);const addons=[...document.querySelectorAll('.addon-check:checked')].map(x=>Number(x.value));saveIds(base,addons);const o=calcOrder();renderSelected('selected-items',o);const a=document.getElementById('subtotal-price'),b=document.getElementById('discount-value'),c=document.getElementById('total-price');if(a)a.textContent=money(o.subtotal);if(b)b.textContent=o.discountValue?'− '+money(o.discountValue):money(0);if(c)c.textContent=o.pendingPrice?'A confirmar':money(o.total);const msg=document.getElementById('next-discount-message'),val=document.getElementById('next-discount-value'),bar=document.getElementById('discount-progress');const next=[...discounts()].sort((x,y)=>x.min-y.min).find(x=>o.subtotal<x.min);if(msg){if(next){msg.textContent=`Faltam ${money(next.min-o.subtotal)} para ${next.label} de desconto.`;val.textContent=`Meta: ${money(next.min)}`;bar.style.width=Math.min(100,o.subtotal/next.min*100)+'%'}else{msg.textContent='Você já atingiu o maior desconto do combo.';val.textContent=discounts()[0].label;bar.style.width='100%'}}const st=document.getElementById('order-status');if(st)st.textContent=o.items.length>1?'Combo':'1 serviço';const motorAware=document.getElementById('motor-aware');const motorInput=[...document.querySelectorAll('.addon-check')].find(x=>{const s=SERVICES.find(z=>Number(z.id)===Number(x.value));return /motor/i.test(s?.nome||'')});if(motorInput&&motorAware){motorAware.checked=motorInput.checked;motorAware.onchange=()=>{motorInput.checked=motorAware.checked;updateBuilder()}}}
async function goScheduling(){const o=calcOrder();if(!o.base){alert('Escolha um serviço principal.');return}if(o.pendingPrice){alert('Há serviço com preço “a partir de”. Esse atendimento precisa ser confirmado antes do agendamento online.');return}if(o.pendingDuration){alert('Há serviço sem duração cadastrada. Cadastre a duração no painel administrativo antes de agendar.');return}if(hasMotor(o)&&!document.getElementById('motor-aware')?.checked){alert('Para selecionar a lavagem de motor, confirme a ciência dos riscos.');return}window.location.href='agendamento.html'}
function renderBookingSummary(){const o=calcOrder();renderSelected('booking-order',o);const s=document.getElementById('booking-subtotal'),d=document.getElementById('booking-discount'),t=document.getElementById('booking-total'),dl=document.getElementById('duration-label');if(s)s.textContent=money(o.subtotal);if(d)d.textContent=o.discountValue?'− '+money(o.discountValue):money(0);if(t)t.textContent=o.pendingPrice?'A confirmar':money(o.total);if(dl)dl.textContent=o.pendingDuration?'Tempo estimado: a confirmar':`Tempo estimado: ${o.minutes} min`;return o}
async function setupBooking(){const slotsEl=document.getElementById('time-slots');if(!slotsEl)return;await loadConfig();await loadServices();const o=renderBookingSummary();const date=document.getElementById('booking-date'),confirm=document.getElementById('confirm-booking'),feedback=document.getElementById('booking-feedback');const today=new Date();today.setHours(0,0,0,0);date.min=today.toISOString().slice(0,10);let chosen='';async function slots(){chosen='';confirm.disabled=true;if(o.pendingPrice||o.pendingDuration){slotsEl.innerHTML='<span class="empty-state">Este atendimento ainda precisa de preço e/ou duração confirmados no cadastro.</span>';return}if(!date.value){slotsEl.innerHTML='<span class="empty-state">Escolha uma data para consultar os horários.</span>';return}slotsEl.innerHTML='<span class="empty-state">Consultando agenda...</span>';try{const ids=[o.base,...o.addons].map(s=>s.id).join(',');const d=await api(`/api/agendamentos/disponibilidade?date=${encodeURIComponent(date.value)}&service_ids=${encodeURIComponent(ids)}`);if(!d.horarios?.length){slotsEl.innerHTML='<span class="empty-state">Não há horários compatíveis para esta data.</span>';return}slotsEl.innerHTML=d.horarios.map(h=>`<button type="button" class="time-slot" data-time="${h.hora_inicio}"><span>${h.hora_inicio}</span><small>termina ${h.hora_fim}</small></button>`).join('');slotsEl.querySelectorAll('.time-slot').forEach(btn=>btn.onclick=()=>{slotsEl.querySelectorAll('.time-slot').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');chosen=btn.dataset.time;confirm.disabled=false})}catch(e){slotsEl.innerHTML=`<span class="empty-state">${esc(e.message)}</span>`}}date.onchange=slots;await slots();confirm.onclick=async()=>{const name=document.getElementById('customer-name')?.value.trim(),phone=document.getElementById('customer-phone')?.value.trim(),advance=!!document.getElementById('advance-call')?.checked;if(!chosen){feedback.textContent='Escolha um horário.';feedback.className='feedback error';return}if(!name||!phone){feedback.textContent='Preencha nome e WhatsApp para continuar.';feedback.className='feedback error';return}confirm.disabled=true;feedback.textContent='Registrando agendamento...';try{const r=await api('/api/agendamentos',{method:'POST',body:JSON.stringify({data:date.value,hora_inicio:chosen,nome:name,telefone:phone,service_ids:[o.base,...o.addons].map(s=>Number(s.id)),advance_call:advance,motor_aware:hasMotor(o)})});feedback.textContent=`Agendamento confirmado para ${date.value.split('-').reverse().join('/')} às ${chosen}. Código: #${r.agendamento_id}.`;feedback.className='feedback success';localStorage.setItem('imperiumBookingDraft',JSON.stringify({agendamento_id:r.agendamento_id,date:date.value,time:chosen,name,phone,advanceCall:advance}))}catch(e){feedback.textContent=e.message;feedback.className='feedback error';await slots()}}}
async function renderServicesPage(){const el=document.getElementById('services-page');if(!el)return;try{await loadConfig();const services=await loadServices();el.innerHTML=services.length?services.map(s=>`<article class="feature-card"><div class="icon">${esc(String(s.categoria||'SERV').slice(0,2).toUpperCase())}</div><h3>${esc(s.nome)}</h3><p>${esc(s.descricao||'')}</p><strong>${servicePendingPrice(s)?'A partir de '+money(s.preco):money(s.preco)}</strong>${Number(s.duracao_minutos)?`<small style="display:block;margin-top:8px">Tempo estimado: ${s.duracao_minutos} min</small>`:''}</article>`).join(''):'<div class="empty-state">Nenhum serviço ativo cadastrado.</div>'}catch(e){el.innerHTML=`<div class="empty-state">${esc(e.message)}</div>`}}
async function renderReviews(){const el=document.getElementById('reviews-list');if(!el)return;try{const d=await api('/api/avaliacoes');const reviews=d.avaliacoes||[];if(!reviews.length){el.innerHTML='<div class="empty-state">Ainda não há avaliações cadastradas.</div>';return;}el.innerHTML=reviews.map(r=>{const nota=Number(r.nota||0),stars=nota?('★'.repeat(Math.round(nota))+'☆'.repeat(5-Math.round(nota))):'';return `<article class="review-card"><div class="review-image-wrap"><img class="review-image" src="${esc(r.imagem)}" alt="Avaliação pública do IMPÉRIUM no Google" loading="lazy"></div><div class="review-card-body">${stars?`<div class="review-stars" aria-label="Nota ${nota} de 5">${stars}</div>`:''}${r.nome?`<strong class="review-name">${esc(r.nome)}</strong>`:''}<a class="btn btn-secondary review-link" href="${esc(r.link_google)}" target="_blank" rel="noopener noreferrer">Ver esta avaliação no Google →</a></div></article>`}).join('');}catch(e){el.innerHTML='<div class="empty-state">Não foi possível carregar as avaliações agora.</div>';console.error('Avaliações:',e)}}
async function renderPromotionsPage(){const el=document.getElementById('promotions-page');if(!el)return;try{await loadConfig();const d=await api('/api/promocoes');const p=d.promocoes||[];el.innerHTML=p.filter(x=>Number(x.ativo)!==0).map(x=>`<article class="feature-card"><div class="icon">%</div><h3>${esc(x.titulo)}</h3><p>${esc(x.descricao||'')}</p><strong>${money(x.preco)}</strong>${x.preco_anterior?`<small style="display:block;margin-top:8px;text-decoration:line-through">Antes: ${money(x.preco_anterior)}</small>`:''}</article>`).join('')||'<div class="empty-state">Nenhuma promoção ativa no momento.</div>'}catch(e){el.innerHTML=`<div class="empty-state">${esc(e.message)}</div>`}}
function setupMenu(){const b=document.querySelector('.menu-toggle'),n=document.querySelector('.main-nav');if(!b||!n)return;b.onclick=()=>n.classList.toggle('open')}
document.addEventListener('DOMContentLoaded',async()=>{const y=document.getElementById('year');if(y)y.textContent=new Date().getFullYear();setupMenu();await loadConfig();try{if(document.getElementById('reviews-list'))await renderReviews();if(document.getElementById('base-services'))await renderBuilder();else if(document.getElementById('time-slots'))await setupBooking();else if(document.getElementById('services-page'))await renderServicesPage();else if(document.getElementById('promotions-page'))await renderPromotionsPage()}catch(e){console.error(e)}});
